# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370bc848ea660b3cb136514280f9832de893a09b5507c192030bb2ecf6bc7bcb22ed9d0c56a7fb07ef02b342b9e31775a2a1dbc7541ea3eebf08178b2ae491bc

test:
  secret_key_base: 63f9488be139a25b6222e99f81507983e3a05e24bc5161eec35b900a99ef36ed01f0edc9e9c213e0509731fd1edd42bd5bc2bb53a8b77146746bedbc762bd4f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
